edition = "2024"
style_edition = "2024"
unstable_features = true

fn_params_layout = "Vertical"
fn_single_line = true

format_macro_matchers = true
format_macro_bodies = true

format_strings = true
hex_literal_case = "Upper"

imports_layout = "Vertical"
imports_granularity = "Module"
group_imports = "StdExternalCrate"

normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

overflow_delimited_expr = true
reorder_impl_items = true

struct_lit_single_line = false
use_field_init_shorthand = true

use_try_shorthand = true
